# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='clean_file',
            field=models.FileField(null=True, upload_to=main.models.file_path),
        ),
    ]
